# Generated by Django 4.2.30 on 2026-05-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="Singer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Singer Name")),
                (
                    "photo",
                    models.ImageField(
                        upload_to="singers/", verbose_name="Singer Photo"
                    ),
                ),
                ("bio", models.TextField(verbose_name="Biography")),
                (
                    "experience_years",
                    models.IntegerField(default=0, verbose_name="Years of Experience"),
                ),
                (
                    "price_per_event",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price Per Event (₹)",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=15, verbose_name="Contact Phone"),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram Link"
                    ),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, null=True, verbose_name="YouTube Link"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Available for Booking"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Featured Singer"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="singers.genre",
                    ),
                ),
            ],
            options={
                "ordering": ["-featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="SingerGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="singers/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="singers.singer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Singer Gallery",
            },
        ),
    ]
