# Generated by Django 4.2.30 on 2026-06-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singers", "0005_singerlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video", models.FileField(upload_to="gallery_videos/")),
            ],
        ),
    ]
